<#
.SYNOPSIS
    Generates (or verifies) a SHA-256 manifest for every executable/binary/archive
    shipped with the Atlas playbook.

.DESCRIPTION
    Walks src/playbook/Executables and emits a manifest of the form:
        <SHA256>  <relative-path>
    plus a JSON version used by the SBOM generator.

.PARAMETER PlaybookRoot
    Path to src/playbook.

.PARAMETER ManifestPath
    Where to write the manifest. Default: AtlasModules/Other/hashes.sha256.

.PARAMETER Verify
    If set, verify against an existing manifest instead of writing one.
    Returns exit code 0 on match, 1 on mismatch.
#>

[CmdletBinding()]
param(
    [string]$PlaybookRoot,
    [string]$ManifestPath,
    [switch]$Verify
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $PlaybookRoot) {
    $PlaybookRoot = Resolve-Path (Join-Path $PSScriptRoot '..' '..' 'playbook')
}
$binRoot = Join-Path $PlaybookRoot 'Executables'
if (-not $ManifestPath) {
    $ManifestPath = Join-Path $binRoot 'AtlasModules/Other/hashes.sha256'
}

# Extensions considered "binary / integrity-sensitive"
$binaryExts = @('.exe','.dll','.zip','.cab','.msi','.msu','.sys','.ocx','.appx','.msix','.psm1','.psd1')
# Also include our well-known scripts that run elevated
$scriptExts = @('.ps1','.cmd','.bat')

$allExts = $binaryExts + $scriptExts | Select-Object -Unique

$files = Get-ChildItem -Path $binRoot -Recurse -File | Where-Object {
    $allExts -contains $_.Extension.ToLowerInvariant()
} | Sort-Object FullName

if ($Verify) {
    if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) {
        Write-Host "Manifest not found: $ManifestPath" -ForegroundColor Red
        exit 2
    }
    $errors = 0
    foreach ($line in Get-Content -LiteralPath $ManifestPath) {
        $t = $line.Trim()
        if (-not $t -or $t.StartsWith('#')) { continue }
        $parts = $t -split '\s+',2
        $expected = $parts[0].ToUpperInvariant()
        $rel = $parts[1]
        $abs = Join-Path $binRoot $rel
        if (-not (Test-Path -LiteralPath $abs)) {
            Write-Host ("MISSING   {0}" -f $rel) -ForegroundColor Red
            $errors++
            continue
        }
        $actual = (Get-FileHash -LiteralPath $abs -Algorithm SHA256).Hash.ToUpperInvariant()
        if ($actual -ne $expected) {
            Write-Host ("MISMATCH  {0}  expected={1}  actual={2}" -f $rel, $expected, $actual) -ForegroundColor Red
            $errors++
        }
    }
    # Also warn about new untracked binaries
    $tracked = @{}
    Get-Content -LiteralPath $ManifestPath | ForEach-Object {
        $t = $_.Trim()
        if ($t -and -not $t.StartsWith('#')) {
            $p = ($t -split '\s+',2)[1]
            if ($p) { $tracked[$p] = $true }
        }
    }
    foreach ($f in $files) {
        $rel = $f.FullName.Substring($binRoot.Length).TrimStart('\','/').Replace('\','/')
        if (-not $tracked.ContainsKey($rel)) {
            Write-Host ("UNTRACKED {0}" -f $rel) -ForegroundColor Yellow
        }
    }
    if ($errors -gt 0) { exit 1 }
    Write-Host "All hashes match." -ForegroundColor Green
    exit 0
}

# Generate
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# Atlas binary / script hash manifest')
$lines.Add('# Generated by scripts/ci/New-AtlasHashManifest.ps1')
$lines.Add(('# Generated at: ' + (Get-Date).ToString('o')))
$lines.Add('# Format: <SHA256>  <relative-path>')

$jsonManifest = [ordered]@{}

foreach ($f in $files) {
    $rel = $f.FullName.Substring($binRoot.Length).TrimStart('\','/').Replace('\','/')
    $hash = (Get-FileHash -LiteralPath $f.FullName -Algorithm SHA256).Hash.ToUpperInvariant()
    $lines.Add(("{0}  {1}" -f $hash, $rel))
    $jsonManifest[$rel] = [ordered]@{
        sha256 = $hash
        size   = $f.Length
    }
}

New-Item -ItemType Directory -Path (Split-Path $ManifestPath -Parent) -Force | Out-Null
$lines | Out-File -FilePath $ManifestPath -Encoding ascii -Force
$jsonPath = [System.IO.Path]::ChangeExtension($ManifestPath, '.json')
$jsonManifest | ConvertTo-Json -Depth 4 | Out-File -FilePath $jsonPath -Encoding utf8 -Force

Write-Host ("Manifest written to {0} ({1} entries)" -f $ManifestPath, $files.Count)
